# Upload test results and coverage reports to codecov.io
name: Sync codecov
run-name: Sync codecov by @${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install node packages
        run: npm ci
      - name: Run test and collect coverage
        run: npm test -- --ci --coverage
      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: ./test-results/junit.xml
          name: codecov-umbrella-test-results
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
